<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0;net9.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PackageId>TL.MiddlewareLibrary</PackageId>
    <Version>0.1.0</Version>
    <Authors>Thaylon Lopes</Authors>
    <Company>Thaylon Lopes</Company>
    <Title>TL.MiddlewareLibrary</Title>
    <Description>Biblioteca modular de middlewares para ASP.NET Core (.NET 6, .NET 8 e .NET 9) com foco em diagnósticos de latência, controle de taxa por IP, cache em memória e padronização de respostas de erro com ProblemDetails.</Description>
    <PackageTags>aspnetcore;middleware;problem-details;rate-limiting;caching;timing;authentication;http;zero-allocation</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/thaylonlopes/TL.MiddlewareLibrary</PackageProjectUrl>
    <RepositoryUrl>https://github.com/thaylonlopes/TL.MiddlewareLibrary</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\assets\icon.png" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <!-- Framework Nativo ASP.NET Core -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <Compile Remove="**\*.Net8.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'net6.0'">
    <Compile Remove="**\*.Net6.cs" />
  </ItemGroup>

</Project>
